export const GET_MEALS = 'GET_MEALS'
export const GET_MEAL_BY_ID = 'GET_MEAL_BY_ID'
export const ADD_MEAL = 'ADD_MEAL'
export const DELETE_MEAL = 'DELETE_MEAL'
export const MEALS_LOADING = 'MEALS_LOADING'